#!/bin/bash
find . -type f -iname '*.gif' -printf "%f\n" | rev | cut -c 5- | rev | tr '[:upper:]' '[:lower:]' | tr '\n' '\0' | xargs -0 ls -S1 --format=single-column | rev | cut -c 5- | rev && printf "\n"
